name: Update Mozilla Included CA Certificate List

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Update Mozilla Included CA Certificate List
      run: go generate .

    - name: Commit changes
      id: commit_changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Lucas Bremgartner
        author_email: lucas@bremis.ch
        message: 'Auto Update Mozilla Included CA Certificate List'
        add: 'embedded/data.go'

    - name: Bump version and push tag
      if: ${{ steps.commit_changes.outputs.committed == 'true' && steps.commit_changes.outputs.pushed == 'true' }}
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_sha: ${{ steps.commit_changes.outputs.commit_long_sha }}
